apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/
patchesStrategicMerge:
- manifest-repo-uri-patch.yaml
configMapGenerator:
- name: manifest-uri-cm
  env: environment.env
vars:
- name: MANIFEST_REPO_URI-envvar
  objref:
    kind: ConfigMap
    name: manifest-uri-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.MANIFEST_REPO_URI
configurations:
- varrefs.yaml



