apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- imagepullsecret.yaml
- kfctl_hcp_istio.yaml
configMapGenerator:
- name: kfctl-hcp-istio-kustomize-cm
  env: environment.env
vars:
- name: AIRGAP_REGISTRY-envvar
  objref:
    kind: ConfigMap
    name: kfctl-hcp-istio-kustomize-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRGAP_REGISTRY
configurations:
- varrefs.yaml
